### ISSUE TITLE
Fix rounding error when converting to hex

### ISSUE THREAD

**Issue by michaelshmitty** [Dustproof/dustcube#2]
The measurements are converted to a hexadecimal representation for transmission over the Lora network.
During the conversion however, a rounding occurs (possibly due to use of floats).
See:
![_dev_cu_usbmodem1421__arduino_genuino_uno_](https://cloud.githubusercontent.com/assets/114845/13010716/897261a0-d1a3-11e5-92cc-9fe64be6f0c3.png)

**Comment by michaelshmitty** [comment]
@framb00s I've also created this issue for the rounding error bug.

**Comment by framb00s** [comment]
Michael line215  'int rP = ratioP1 * 100; // convert P1 ratio to an integer'
should be  int rP = (ratioP1+ 0.005) * 100; // convert P1 ratio to an integer
and line 217 should be 'rP = (ratioP2+ 0.005) * 100; // convert P2 ratio to an integer'

Floats are similarly printed as ASCII digits, defaulting to two decimal places. 
So when we see 0.25 it can be any number between 0.245 and 0.254.
So with adding 0.005 the numbers between 0.245 and 249 x 100 becomes integer 25 
and the numbers between 0.250 and 0.254 x 100 stay integer 25

**Comment by michaelshmitty** [comment]
@framb00s good thinking! Would you like to practice using branches and fix this bug?

**Comment by framb00s** [comment]
The rounding error should be fixed
;)

2016-02-12 17:05 GMT+01:00 Michael Smith <notifications@github.com>:

**Comment by michaelshmitty** [comment]
Great, well done!

Just a note, no criticism: I see you didn't use a branch for this, nevermind now. But next time try to create a branch, commit the changes in the branch and merge it into master and push. Or push the branch to GitHub and open a pull request (more on that later).
Direct commits into master are generally not considered best practice in git.
I'll close this issue now. You can also close or comment on issues through your commit message. More on that later.
